/**
 * Fetch all the Open Physician Visits for the Users with profile INDSU Sales Rep, to notify users 
 * regarding open Physician visits for the last day for which they can complete the Physician visit, considering here
 * A Sales Rep can compelte a visit today upto last 3 days. After today he will not be able to send the mail 
 *
 *   Author             |Author-Email                                      |Date       |Comment
 *   -------------------|--------------------------------------------------|-----------|--------------------------------------------------
 *   Raviteja Vakity    |raviteja.vakity@bausch.com                        |17.12.2013 |First Draft 
 *   Neha Jain          |neha.jain@bausch.com                              |23-04-2014 |Removed the code as is of no use now, also tried to delete from PD but not possible 
 *
 * Test Class -- Test_ScheduleNotifyPhysicianVisits
 * Scheduler Class -- clsNotifyOpenPhysicianScheduler
 */
 


 public Class CtrlNotifyOpenPhysicianVisits {
     public CtrlNotifyOpenPhysicianVisits (){
         integer a = 10;
     }
 }