/*
* 
* Test class for PhysicianVisits Triggers PhysicianVisit_BU_UpdateCompetitorInformation
* 
* Author                        |Author-Email                                       |Date        |Comment
* ------------------------------|---------------------------------------------------|------------|----------------------------------------------------
* Neha Jain                    |neha.jain@bausch.com                               |23.04.2014  |First Draft
*/

@isTest
private class Test_CtrlNotifyOpenPhysicianVisits  {
   static testMethod void myUnitTest() {
        CtrlNotifyOpenPhysicianVisits  c = new CtrlNotifyOpenPhysicianVisits ();
    }
}